[MFLOG|0|2025-04-17T08:56:29.057639Z|runtime|48275c65-b7e6-408e-b9ec-c73b30ae9a09]<flow InitFlow step ingenieria_de_datos> failed:
[MFLOG|0|2025-04-17T08:56:29.071708Z|runtime|79d6a153-7896-4b27-9d7b-28f6407c061d]    Internal error
[MFLOG|0|2025-04-17T08:56:29.073440Z|runtime|6e8c4d28-486f-4338-9aba-1d44439a34e6]Traceback (most recent call last):
[MFLOG|0|2025-04-17T08:56:29.073595Z|runtime|abc7ec6a-e42a-4dcc-824a-2bd6ec801c84]  File "/home/clau/proyectos/metaflow/Practica-SIE-METAFLOW/venv/lib/python3.12/site-packages/metaflow/cli.py", line 611, in main
[MFLOG|0|2025-04-17T08:56:29.073698Z|runtime|0dc7025d-2ad6-47c7-b511-1c8fa884098e]    start(auto_envvar_prefix="METAFLOW", obj=state)
[MFLOG|0|2025-04-17T08:56:29.073895Z|runtime|1e269306-9dbd-4834-8aa7-e80488dd3172]  File "/home/clau/proyectos/metaflow/Practica-SIE-METAFLOW/venv/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 829, in __call__
[MFLOG|0|2025-04-17T08:56:29.074069Z|runtime|80794003-168e-4f5f-a9f6-9418f9871ddd]    return self.main(args, kwargs)
[MFLOG|0|2025-04-17T08:56:29.074307Z|runtime|031ff687-3b9a-478b-8f1b-9fc964c0c015]           ^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-17T08:56:29.074492Z|runtime|7e02d781-cee3-4433-b42a-8adf7fb678ed]  File "/home/clau/proyectos/metaflow/Practica-SIE-METAFLOW/venv/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 782, in main
[MFLOG|0|2025-04-17T08:56:29.074740Z|runtime|e9d5b62b-153c-4b1b-aa86-11634bafc8ea]    rv = self.invoke(ctx)
[MFLOG|0|2025-04-17T08:56:29.074964Z|runtime|389af5c5-edb4-4d50-8664-f163cacca726]         ^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-17T08:56:29.075252Z|runtime|c6194cc0-dee7-455b-86e6-83b2b69f80f6]  File "/home/clau/proyectos/metaflow/Practica-SIE-METAFLOW/venv/lib/python3.12/site-packages/metaflow/cli_components/utils.py", line 69, in invoke
[MFLOG|0|2025-04-17T08:56:29.075483Z|runtime|ad4511fa-b4f6-45f6-8c8e-1dd5aaab2c93]    return _process_result(sub_ctx.command.invoke(sub_ctx))
[MFLOG|0|2025-04-17T08:56:29.075723Z|runtime|f3bdd652-86a6-46c6-a57e-b44fe7d6cafa]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-17T08:56:29.076320Z|runtime|fd7cb932-5090-4468-b33f-22d4a7f91246]  File "/home/clau/proyectos/metaflow/Practica-SIE-METAFLOW/venv/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 1066, in invoke
[MFLOG|0|2025-04-17T08:56:29.076528Z|runtime|dcf9889e-0e2b-4343-9dc1-55639a9acb84]    return ctx.invoke(self.callback, ctx.params)
[MFLOG|0|2025-04-17T08:56:29.076664Z|runtime|3c165449-e015-4125-b07d-364a125bed34]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-17T08:56:29.076822Z|runtime|46af8e53-05be-4867-ac7f-669dffdb5ae9]  File "/home/clau/proyectos/metaflow/Practica-SIE-METAFLOW/venv/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 610, in invoke
[MFLOG|0|2025-04-17T08:56:29.077050Z|runtime|c7a961c5-2604-4fb7-af37-d3774302da05]    return callback(args, kwargs)
[MFLOG|0|2025-04-17T08:56:29.253007Z|runtime|6855ae63-ce39-4a57-84c9-1dc2bebf7830]           ^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-17T08:56:29.253363Z|runtime|9a0be292-c2cf-4905-b3bf-b97dd433ac85]  File "/home/clau/proyectos/metaflow/Practica-SIE-METAFLOW/venv/lib/python3.12/site-packages/metaflow/tracing/__init__.py", line 27, in wrapper_func
[MFLOG|0|2025-04-17T08:56:29.253798Z|runtime|cd7d1322-4431-406f-adf3-3cb41b845c8e]    return func(args, kwargs)
[MFLOG|0|2025-04-17T08:56:29.254158Z|runtime|1cf20307-8558-4ee6-9e41-d72f96c07aeb]           ^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-17T08:56:29.254467Z|runtime|d519daf6-6526-4b10-a3bd-9beb65eec1ee]  File "/home/clau/proyectos/metaflow/Practica-SIE-METAFLOW/venv/lib/python3.12/site-packages/metaflow/_vendor/click/decorators.py", line 21, in new_func
[MFLOG|0|2025-04-17T08:56:29.254611Z|runtime|89707cf0-be1a-4098-b4b1-9816f84e8acf]    return f(get_current_context(), args, kwargs)
[MFLOG|0|2025-04-17T08:56:29.254722Z|runtime|49cb013b-a9b4-44c2-a0dc-dc6031b6bdf0]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-17T08:56:29.254893Z|runtime|9f3f30f5-cde0-4e63-bd67-c452c2924adf]  File "/home/clau/proyectos/metaflow/Practica-SIE-METAFLOW/venv/lib/python3.12/site-packages/metaflow/cli_components/step_cmd.py", line 167, in step
[MFLOG|0|2025-04-17T08:56:29.255072Z|runtime|ffe5d8d2-7f8d-4c7d-97ad-57084d89fa61]    task.run_step(
[MFLOG|0|2025-04-17T08:56:29.255260Z|runtime|22becfbe-d111-4ef9-9c93-d6a937c6f39d]  File "/home/clau/proyectos/metaflow/Practica-SIE-METAFLOW/venv/lib/python3.12/site-packages/metaflow/task.py", line 672, in run_step
[MFLOG|0|2025-04-17T08:56:29.255447Z|runtime|9760b573-eb1b-47d0-a9bc-3b8fe5bb4459]    self._exec_step_function(step_func)
[MFLOG|0|2025-04-17T08:56:29.255607Z|runtime|5daa1341-29be-4917-8ac1-16113e3e749e]  File "/home/clau/proyectos/metaflow/Practica-SIE-METAFLOW/venv/lib/python3.12/site-packages/metaflow/task.py", line 62, in _exec_step_function
[MFLOG|0|2025-04-17T08:56:29.255796Z|runtime|a55a9d55-2e9f-413a-aa25-b2ead9065835]    step_function()
[MFLOG|0|2025-04-17T08:56:29.255983Z|runtime|0f43af94-9fbe-4a30-85c2-b86e70b53ea3]  File "/home/clau/proyectos/metaflow/Practica-SIE-METAFLOW/FLOWS/preprocesamiento.py", line 28, in ingenieria_de_datos
[MFLOG|0|2025-04-17T08:56:29.256142Z|runtime|13bddb1a-efef-4b51-8fd2-6a9174a32762]    clasificacion = pd.read_csv('data/clasificacion.csv')
[MFLOG|0|2025-04-17T08:56:29.256321Z|runtime|e57dfaee-817f-49a4-98ea-bd8b0a62d42e]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-17T08:56:29.256513Z|runtime|17116dc8-892f-4884-810e-caebbef2c576]  File "/home/clau/proyectos/metaflow/Practica-SIE-METAFLOW/venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
[MFLOG|0|2025-04-17T08:56:29.256699Z|runtime|a2a2b558-5b76-484c-8bbd-4620b21a221a]    return _read(filepath_or_buffer, kwds)
[MFLOG|0|2025-04-17T08:56:29.256882Z|runtime|496b21de-0745-428a-9ccb-d44cdb5ee908]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-17T08:56:29.257066Z|runtime|452d798a-f324-4c72-8c92-abe761c868bf]  File "/home/clau/proyectos/metaflow/Practica-SIE-METAFLOW/venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
[MFLOG|0|2025-04-17T08:56:29.257294Z|runtime|542aa4a1-b5a7-43cf-9548-8d767415a4e7]    parser = TextFileReader(filepath_or_buffer, kwds)
[MFLOG|0|2025-04-17T08:56:29.257467Z|runtime|0444a56e-6bed-4983-969c-ba83c25dff14]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-17T08:56:29.257571Z|runtime|73c64094-e83c-4606-847f-dfa443273c20]  File "/home/clau/proyectos/metaflow/Practica-SIE-METAFLOW/venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
[MFLOG|0|2025-04-17T08:56:29.257728Z|runtime|0d5bc8d9-140f-4be4-8f57-cbc6e229038d]    self._engine = self._make_engine(f, self.engine)
[MFLOG|0|2025-04-17T08:56:29.257885Z|runtime|55aa29db-b324-4f2a-aea5-bb1612d2f394]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-17T08:56:29.258039Z|runtime|52eec06e-e2a8-4d7c-b7da-04e8c8a8be6d]  File "/home/clau/proyectos/metaflow/Practica-SIE-METAFLOW/venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
[MFLOG|0|2025-04-17T08:56:29.258188Z|runtime|f26020a5-7ca0-47b9-b40b-cbca0ae882c0]    self.handles = get_handle(
[MFLOG|0|2025-04-17T08:56:29.258373Z|runtime|893ec28c-9c4d-413a-8211-4ea8a728dede]                   ^^^^^^^^^^^
[MFLOG|0|2025-04-17T08:56:29.258582Z|runtime|5d62f7a5-0dd7-4ea1-8894-7dc9296cf348]  File "/home/clau/proyectos/metaflow/Practica-SIE-METAFLOW/venv/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle
[MFLOG|0|2025-04-17T08:56:29.258784Z|runtime|443108c5-a3c1-4bc4-9df3-4cad0cab7b3f]    handle = open(
[MFLOG|0|2025-04-17T08:56:29.259020Z|runtime|a085ac34-24bf-4f89-848b-4e7226977a02]             ^^^^^
[MFLOG|0|2025-04-17T08:56:29.259264Z|runtime|cbf19b7e-bdb5-4561-a9b3-4f13a7e857a2]FileNotFoundError: [Errno 2] No such file or directory: 'data/clasificacion.csv'
[MFLOG|0|2025-04-17T08:56:29.259527Z|runtime|003b6932-0b0a-442e-99a0-de8dea58044d]
[MFLOG|0|2025-04-17T08:56:29.260312Z|runtime|6cb60d70-a59e-4da7-ae94-edea03d68a71]Task failed.